version: "3.7"

services:
  traefik:
    build: traefik.docker
    image: traefik:local
    depends_on:
      - pebble
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./certs:/certs
      - ./certs/ca:/usr/local/share/ca-certificates:ro
    ports:
      - "127.0.0.1:${TRAEFIK_PORT_HTTP:-80}:80"
      - "::1:${TRAEFIK_PORT_HTTP:-80}:80"
      - "127.0.0.1:${TRAEFIK_PORT_HTTPS:-443}:443"
      - "::1:${TRAEFIK_PORT_HTTPS:-443}:443"
      - "127.0.0.1:${TRAEFIK_PORT_DASHBOARD:-8080}:8080"
      - "::1:${TRAEFIK_PORT_DASHBOARD:-8080}:8080"
    container_name: traefik
    restart: always
    labels:
      - traefik.enable=false

  pebble:
    image: letsencrypt/pebble:latest
    container_name: pebble
    restart: always
    volumes:
      - ./certs:/var/pebble/certs
      - ./pebble.json:/pebble.json
    ports:
      - "${PEBBLE_PORT:-127.0.0.1:14000}:14000"
      - "${PEBBLE_MGMT_PORT:-127.0.0.1:15000}:15000"
    environment:
      PEBBLE_VA_ALWAYS_VALID: 1
      PEBBLE_VA_NOSLEEP: 1
      PEBBLE_WFE_NONCEREJECT: 0
    command: pebble -config /pebble.json

networks:
  default:
    external:
      name: traefik
