version: "3.7"

services:
  traefik:
    build: traefik.docker
    image: traefik:local
    depends_on:
      - pebble
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./certs:/certs
      - ./certs/ca:/usr/local/share/ca-certificates:ro
    ports:
      - "127.0.0.1:${TRAEFIK_PORT_HTTP:-80}:80"
      - "::1:${TRAEFIK_PORT_HTTP:-80}:80"
      - "127.0.0.1:${TRAEFIK_PORT_HTTPS:-443}:443"
      - "::1:${TRAEFIK_PORT_HTTPS:-443}:443"
      - "127.0.0.1:${TRAEFIK_PORT_DASHBOARD:-8080}:8080"
      - "::1:${TRAEFIK_PORT_DASHBOARD:-8080}:8080"
    container_name: traefik
    restart: always
    labels:
      traefik.enable: true
      ## Uncomment this for permanent redirect from http:// to https://
      ## Also make sure your container is registered on web-secure entrypoint
      ## otherwise, you request will fall into whoami container.
      # traefik.http.routers.traefik.entrypoints: web
      # traefik.http.routers.traefik.rule: HostRegexp(`{any:.*}`)
      # traefik.http.routers.traefik.priority: 999
      # traefik.http.routers.traefik.middlewares: traefik-redirect
      # traefik.http.middlewares.traefik-redirect.redirectscheme.scheme: https

  unbound:
    container_name: unbound
    build: unbound.docker
    image: unbound:local
    ports:
      - "127.0.2.53:53:53/udp"

  pebble:
    image: letsencrypt/pebble:latest
    container_name: pebble
    restart: always
    volumes:
      - ./certs:/var/pebble/certs
      - ./pebble.json:/pebble.json
    ports:
      - "${PEBBLE_PORT:-127.0.0.1:14000}:14000"
      - "${PEBBLE_MGMT_PORT:-127.0.0.1:15000}:15000"
    environment:
      PEBBLE_VA_ALWAYS_VALID: 1
      PEBBLE_VA_NOSLEEP: 1
      PEBBLE_WFE_NONCEREJECT: 0
    command: pebble -config /pebble.json

  whoami:
    image: containous/whoami:latest
    container_name: whoami
    restart: always
    labels:
      traefik.http.routers.whoami.entrypoints: web
      traefik.http.routers.whoami.rule: HostRegexp(`{any:.*}`)
      traefik.http.routers.whoami.priority: 1
      traefik.http.routers.whoami.middlewares: whoami-redirectscheme
      traefik.http.middlewares.whoami-redirectscheme.redirectscheme.scheme: https
      traefik.http.routers.whoami-https.entrypoints: web-secure
      traefik.http.routers.whoami-https.rule: HostRegexp(`{any:.*}`)
      traefik.http.routers.whoami-https.priority: 1
      traefik.http.routers.whoami-https.tls.certresolver: letsencrypt

networks:
  default:
    external:
      name: traefik
