version: "3"

services:
  traefik:
    build: traefik.docker
    image: traefik:local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik/traefik.toml:/traefik.toml
      - /etc/traefik/certs:/certs
      - /etc/traefik/certs/ca:/usr/local/share/ca-certificates:ro
    ports:
      - 127.0.0.1:443:443
      - 127.0.0.1:80:80
      - 127.0.0.1:8080:8080
    container_name: traefik
    restart: always
    labels:
      - traefik.enable=false

  pebble:
    image: letsencrypt/pebble:latest
    container_name: pebble
    restart: always
    volumes:
      - /etc/traefik/certs:/var/pebble/certs
      - /etc/traefik/pebble.json:/pebble.json
    environment:
      PEBBLE_VA_ALWAYS_VALID: 1
      PEBBLE_VA_NOSLEEP: 1
      PEBBLE_WFE_NONCEREJECT: 0
    command: pebble -config /pebble.json

networks:
  default:
    external:
      name: traefik_webgateway
