[serversTransport]
  insecureSkipVerify = true
  rootCAs = ["/certs/rootCA.pem"]

[api]
  insecure = true
  dashboard = true

[pilot]
  # disable traefik pilot (SasS) feature
  dashboard = false

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"
    [entryPoints.web-secure.http.tls]

  [entryPoints.ssh]
    address = ":22"
  [entryPoints.ssh-alt]
    address = ":2222"

[http.middlewares]
  [http.middlewares.redirect.redirectScheme]
    scheme = "https"

[providers.docker]
  exposedByDefault = false

[log]
  level = "INFO"

[accesslog]

[providers]
  [providers.file]
    filename = "/etc/traefik/traefik_dynamic_conf.toml"
