[serversTransport]
  rootCAs = ["/certs/ca/cert.pem"]

[api]
  insecure = true
  dashboard = true


[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"


[http.middlewares]
  [http.middlewares.redirect.redirectScheme]
    scheme = "https"

[certificatesResolvers.pebble.acme]
  email = "test@docker.localhost"
  storage = "/var/run/acme.json"
  caServer = "https://pebble:14000/dir"
  [certificatesResolvers.pebble.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"


[providers.docker]

[log]
  level = "DEBUG"

[accesslog]
